# First run
# echo HOST_ADDR=$(curl -s https://api.ipify.org) > .env && sudo docker-compose up -d && sudo docker-compose exec -d dockovpn wget -O /doc/Dockovpn/client.ovpn localhost:8090
# echo HOST_ADDR=0.0.0.0 > .env && sudo docker-compose up -d && sudo docker-compose exec -d dockovpn wget -O /doc/Dockovpn/client.ovpn localhost:8090

version: '3'
services:
  dockovpn:
    image: openvpn
    build: .
    cap_add:
        - NET_ADMIN
    ports:
        - 1194:1194/udp
    environment:
        HOST_ADDR: ${HOST_ADDR} 
    volumes:
        - ./openvpn_conf:/doc/Dockovpn
    restart: always
